import * as core from '@actions/core';
import * as fs from 'fs';
import * as path from 'path';
import { runCommand } from '../utils/exec';

/**
 * Well-known Android SDK locations by platform.
 * GitHub Actions runners use the first entry for each platform.
 */
const SDK_SEARCH_PATHS: Record<string, string[]> = {
  linux: [
    '/usr/local/lib/android/sdk',    // GitHub Actions ubuntu-latest
    '/home/runner/Android/Sdk',       // Some act images
    `${process.env.HOME}/Android/Sdk`, // Default Android Studio on Linux
  ],
  darwin: [
    `${process.env.HOME}/Library/Android/sdk`, // Default Android Studio on macOS
  ],
};

/**
 * Detect the Android SDK location.
 *
 * Checks in order:
 * 1. ANDROID_HOME environment variable (already set)
 * 2. ANDROID_SDK_ROOT environment variable (deprecated but still used)
 * 3. Well-known paths for the current platform
 *
 * @returns The SDK path, or null if not found.
 */
export function detectAndroidSdk(): string | null {
  // Check existing env vars
  const fromEnv = process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT;
  if (fromEnv && fs.existsSync(fromEnv)) {
    return fromEnv;
  }

  // Search well-known paths
  const platform = process.platform === 'darwin' ? 'darwin' : 'linux';
  const searchPaths = SDK_SEARCH_PATHS[platform] || [];

  for (const sdkPath of searchPaths) {
    if (fs.existsSync(sdkPath)) {
      return sdkPath;
    }
  }

  return null;
}

/**
 * Ensure ANDROID_HOME is set and the SDK is available.
 *
 * On GitHub Actions runners, the SDK is pre-installed but ANDROID_HOME
 * may not be exported in all contexts (e.g. act Docker images).
 * This function detects the SDK and exports the environment variable.
 */
export async function setupAndroidSdk(): Promise<void> {
  // Check if already set and valid
  if (process.env.ANDROID_HOME && fs.existsSync(process.env.ANDROID_HOME)) {
    core.info(`ANDROID_HOME already set: ${process.env.ANDROID_HOME}`);
    return;
  }

  const sdkPath = detectAndroidSdk();

  if (sdkPath) {
    core.info(`Detected Android SDK at: ${sdkPath}`);
    core.exportVariable('ANDROID_HOME', sdkPath);
    core.exportVariable('ANDROID_SDK_ROOT', sdkPath);
    // Add platform-tools and cmdline-tools to PATH
    const platformTools = path.join(sdkPath, 'platform-tools');
    const cmdlineTools = path.join(sdkPath, 'cmdline-tools', 'latest', 'bin');
    if (fs.existsSync(platformTools)) {
      core.addPath(platformTools);
    }
    if (fs.existsSync(cmdlineTools)) {
      core.addPath(cmdlineTools);
    }
    return;
  }

  // SDK not found — try to provide a helpful error
  const platform = process.platform === 'darwin' ? 'darwin' : 'linux';
  const searchedPaths = SDK_SEARCH_PATHS[platform] || [];

  core.error(
    'Android SDK not found. Searched:\n' +
    `  - ANDROID_HOME env var: ${process.env.ANDROID_HOME || '(not set)'}\n` +
    `  - ANDROID_SDK_ROOT env var: ${process.env.ANDROID_SDK_ROOT || '(not set)'}\n` +
    searchedPaths.map(p => `  - ${p}`).join('\n') + '\n\n' +
    'On GitHub Actions runners, the SDK is pre-installed.\n' +
    'For local testing with act, try:\n' +
    '  docker run with -e ANDROID_HOME=/usr/local/lib/android/sdk\n' +
    'Or install the SDK: https://developer.android.com/studio/command-line/sdkmanager'
  );

  throw new Error('Android SDK not found. Set ANDROID_HOME or install the Android SDK.');
}

/**
 * Write a local.properties file pointing to the Android SDK.
 * Gradle uses this to find the SDK when ANDROID_HOME is not set
 * in the process environment (e.g. when Fastlane spawns Gradle).
 */
export async function writeLocalProperties(projectDir: string): Promise<void> {
  const sdkPath = process.env.ANDROID_HOME;
  if (!sdkPath) {
    core.warning('ANDROID_HOME not set — skipping local.properties generation');
    return;
  }

  const localPropsPath = path.join(projectDir, 'android', 'local.properties');
  const androidDir = path.join(projectDir, 'android');

  // Only write if android/ directory exists (after prebuild)
  if (!fs.existsSync(androidDir)) {
    return;
  }

  // Escape backslashes for Windows paths (unlikely in our case but correct)
  const escapedPath = sdkPath.replace(/\\/g, '\\\\');
  const content = `# Generated by app-build action\nsdk.dir=${escapedPath}\n`;

  await fs.promises.writeFile(localPropsPath, content, 'utf8');
  core.info(`Wrote Android SDK path to ${localPropsPath}`);
}
